create type public.delivery_method as enum ('nova_poshta', 'ukrposhta', 'courier');
create type public.payment_method as enum ('bank_transfer', 'cash_on_delivery');
create type public.payment_status as enum ('pending', 'awaiting_confirmation', 'paid', 'cash_on_delivery', 'failed');
create type public.order_status as enum ('new', 'confirmed', 'payment_pending', 'paid', 'processing', 'shipped', 'delivered', 'cancelled');

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table public.categories (
  id uuid primary key default gen_random_uuid(),
  name text not null check (length(trim(name)) between 1 and 120),
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  description text not null default '',
  image_url text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.products (
  id uuid primary key default gen_random_uuid(),
  category_id uuid not null references public.categories(id) on delete restrict,
  name text not null check (length(trim(name)) between 1 and 200),
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  description text not null default '',
  composition text not null default '',
  care_instructions text not null default '',
  price numeric(12, 2) not null check (price >= 0),
  old_price numeric(12, 2) check (old_price is null or old_price >= 0),
  is_published boolean not null default true,
  is_available boolean not null default true,
  is_featured boolean not null default false,
  is_new boolean not null default false,
  is_sale boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.product_images (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products(id) on delete cascade,
  storage_path text not null unique,
  alt text not null default '',
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table public.product_variants (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products(id) on delete cascade,
  sku text not null unique,
  size text not null check (length(trim(size)) between 1 and 40),
  color text not null check (length(trim(color)) between 1 and 80),
  color_hex text not null check (color_hex ~ '^#[0-9A-Fa-f]{6}$'),
  price numeric(12, 2) not null check (price >= 0),
  stock integer not null default 0 check (stock >= 0),
  is_available boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (product_id, size, color)
);

create table public.admin_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity unique,
  first_name text not null check (length(trim(first_name)) between 1 and 80),
  last_name text not null check (length(trim(last_name)) between 1 and 80),
  phone text not null check (phone ~ '^(\+380[0-9]{9}|0[0-9]{9})$'),
  city text not null check (length(trim(city)) between 1 and 100),
  delivery_method public.delivery_method not null,
  delivery_address text not null check (length(trim(delivery_address)) between 1 and 200),
  payment_method public.payment_method not null,
  payment_status public.payment_status not null default 'pending',
  status public.order_status not null default 'new',
  comment text check (comment is null or length(comment) <= 500),
  subtotal numeric(12, 2) not null check (subtotal >= 0),
  delivery_price numeric(12, 2) not null default 0 check (delivery_price >= 0),
  total numeric(12, 2) not null check (total >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (total = subtotal + delivery_price)
);

create table public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id uuid not null references public.products(id) on delete restrict,
  variant_id uuid not null references public.product_variants(id) on delete restrict,
  product_name text not null,
  product_image text,
  size text not null,
  color text not null,
  price numeric(12, 2) not null check (price >= 0),
  quantity integer not null check (quantity > 0),
  subtotal numeric(12, 2) generated always as (price * quantity) stored
);

create table public.store_settings (
  key text primary key check (length(trim(key)) between 1 and 80),
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create index products_category_id_idx on public.products(category_id);
create index products_public_listing_idx on public.products(is_published, is_available, created_at desc);
create index product_images_product_sort_idx on public.product_images(product_id, sort_order);
create index product_variants_product_id_idx on public.product_variants(product_id);
create index product_variants_available_stock_idx on public.product_variants(product_id, is_available, stock);
create index orders_created_at_idx on public.orders(created_at desc);
create index orders_status_created_at_idx on public.orders(status, created_at desc);
create index orders_payment_status_idx on public.orders(payment_status);
create index orders_phone_idx on public.orders(phone);
create index order_items_order_id_idx on public.order_items(order_id);

create trigger categories_set_updated_at before update on public.categories for each row execute function public.set_updated_at();
create trigger products_set_updated_at before update on public.products for each row execute function public.set_updated_at();
create trigger product_variants_set_updated_at before update on public.product_variants for each row execute function public.set_updated_at();
create trigger admin_profiles_set_updated_at before update on public.admin_profiles for each row execute function public.set_updated_at();
create trigger orders_set_updated_at before update on public.orders for each row execute function public.set_updated_at();
create trigger store_settings_set_updated_at before update on public.store_settings for each row execute function public.set_updated_at();

create or replace function public.is_active_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.admin_profiles
    where user_id = (select auth.uid()) and is_active
  );
$$;

revoke all on function public.is_active_admin() from public, anon;
grant execute on function public.is_active_admin() to authenticated;

alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.product_images enable row level security;
alter table public.product_variants enable row level security;
alter table public.admin_profiles enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.store_settings enable row level security;

grant select on public.categories, public.products, public.product_images, public.product_variants to anon, authenticated;
grant all on public.categories, public.products, public.product_images, public.product_variants,
  public.admin_profiles, public.orders, public.order_items, public.store_settings to authenticated;

create policy "Public can read active categories" on public.categories
  for select to anon, authenticated using (is_active);
create policy "Admins manage categories" on public.categories
  for all to authenticated using ((select public.is_active_admin())) with check ((select public.is_active_admin()));

create policy "Public can read published products" on public.products
  for select to anon, authenticated using (is_published);
create policy "Admins manage products" on public.products
  for all to authenticated using ((select public.is_active_admin())) with check ((select public.is_active_admin()));

create policy "Public can read images for published products" on public.product_images
  for select to anon, authenticated using (
    exists (select 1 from public.products p where p.id = product_id and p.is_published)
  );
create policy "Admins manage product images" on public.product_images
  for all to authenticated using ((select public.is_active_admin())) with check ((select public.is_active_admin()));

create policy "Public can read variants for published products" on public.product_variants
  for select to anon, authenticated using (
    exists (select 1 from public.products p where p.id = product_id and p.is_published)
  );
create policy "Admins manage product variants" on public.product_variants
  for all to authenticated using ((select public.is_active_admin())) with check ((select public.is_active_admin()));

create policy "Admins can read own profile" on public.admin_profiles
  for select to authenticated using (user_id = (select auth.uid()));
create policy "Admins manage orders" on public.orders
  for all to authenticated using ((select public.is_active_admin())) with check ((select public.is_active_admin()));
create policy "Admins manage order items" on public.order_items
  for all to authenticated using ((select public.is_active_admin())) with check ((select public.is_active_admin()));
create policy "Admins manage store settings" on public.store_settings
  for all to authenticated using ((select public.is_active_admin())) with check ((select public.is_active_admin()));

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('product-images', 'product-images', true, 10485760, array['image/jpeg', 'image/png', 'image/webp', 'image/avif'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "Admins upload product images" on storage.objects
  for insert to authenticated with check (
    bucket_id = 'product-images' and (select public.is_active_admin())
  );
create policy "Admins update product images" on storage.objects
  for update to authenticated using (
    bucket_id = 'product-images' and (select public.is_active_admin())
  ) with check (
    bucket_id = 'product-images' and (select public.is_active_admin())
  );
create policy "Admins delete product images" on storage.objects
  for delete to authenticated using (
    bucket_id = 'product-images' and (select public.is_active_admin())
  );
